name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] <Short Description>"
labels: ["enhancement"]
projects: ["https://github.com/users/KitanoB/projects/4"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Value / Impact

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Feature
    validations:
      required: true