name: Bug Report
description: Report something that is not working as expected
title: "[Bug] <Short Description>"
labels: ["bug"]
projects: ["https://github.com/users/KitanoB/projects/4"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior

  - type: textarea
    id: environment
    attributes:
      label: Environment

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
    validations:
      required: true